on: [push]
jobs:
  build-and-deploy:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
      - name: Build site
        run: |
          /run/current-system/sw/bin/nix develop --option sandbox false --command bash scripts/build-site.sh /tmp/surface-site
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          /run/wrappers/bin/sudo /run/current-system/sw/bin/deploy-surface /tmp/surface-site
      - name: Upload PDFs to Google Drive
        if: github.ref == 'refs/heads/main'
        run: |
          /run/wrappers/bin/sudo /run/current-system/sw/bin/upload-to-drive /tmp/surface-site
