#!/usr/bin/env bash
# Build all HTML and PDF output from data/ into a single site directory.
# Usage: build-site.sh [output-dir]
#   output-dir defaults to ./site

set -euo pipefail

SURFACE_ROOT="${SURFACE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
SITE_DIR="${1:-$SURFACE_ROOT/site}"

export SURFACE_ROOT

# Brand colour defaults
export BRAND_PRIMARY="${BRAND_PRIMARY:-#6366f1}"
export BRAND_ACCENT="${BRAND_ACCENT:-#a78bfa}"
export BRAND_BG="${BRAND_BG:-#0a0a1a}"
export BRAND_TEXT="${BRAND_TEXT:-#e0e0e0}"

echo "==> Building board HTML"
python3 "$SURFACE_ROOT/modules/board/scripts/board.py" html "$SITE_DIR/board"

echo "==> Generating PDFs"
mkdir -p "$SURFACE_ROOT/downloads"

# Board
python3 "$SURFACE_ROOT/modules/board/scripts/board.py" pdf pack || echo "    (no board data)"
python3 "$SURFACE_ROOT/modules/board/scripts/board.py" pdf resolutions || echo "    (no resolutions)"

# Shares
python3 "$SURFACE_ROOT/modules/shares/scripts/shares.py" pdf table || echo "    (no shares data)"
python3 "$SURFACE_ROOT/modules/shares/scripts/shares.py" pdf history || echo "    (no share history)"
python3 "$SURFACE_ROOT/modules/shares/scripts/shares.py" pdf vesting || echo "    (no vesting data)"

# Company
python3 "$SURFACE_ROOT/modules/company/scripts/company.py" pdf summary || echo "    (no company data)"

# Officers
python3 "$SURFACE_ROOT/modules/officers/scripts/officers.py" pdf register || echo "    (no officers data)"

# Compliance
python3 "$SURFACE_ROOT/modules/compliance/scripts/compliance.py" pdf calendar || echo "    (no compliance data)"

# Charges
python3 "$SURFACE_ROOT/modules/charges/scripts/charges.py" pdf register || echo "    (no charges data)"

# Dividends
python3 "$SURFACE_ROOT/modules/dividends/scripts/dividends.py" pdf register || echo "    (no dividends data)"

# Copy generated PDFs to site
mkdir -p "$SITE_DIR/downloads"
cp -v "$SURFACE_ROOT/downloads/"*.pdf "$SITE_DIR/downloads/" 2>/dev/null || echo "    (no PDFs generated)"

# Generate a top-level index page linking to everything
cat > "$SITE_DIR/index.html" << 'INDEXEOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Surface</title>
<style>
  :root { --bg: #0a0a1a; --text: #e0e0e0; --primary: #6366f1; --accent: #a78bfa; }
  body { font-family: system-ui, sans-serif; background: var(--bg); color: var(--text);
         max-width: 600px; margin: 4rem auto; padding: 0 1rem; }
  a { color: var(--primary); text-decoration: none; }
  a:hover { color: var(--accent); }
  h1 { border-bottom: 2px solid var(--primary); padding-bottom: 0.5rem; }
  ul { list-style: none; padding: 0; }
  li { padding: 0.5rem 0; }
  li::before { content: "→ "; color: var(--accent); }
  .section { margin-top: 2rem; }
</style>
</head>
<body>
<h1>Surface</h1>
<p>Company-as-code output</p>
<div class="section">
  <h2>Board</h2>
  <ul>
    <li><a href="board/">Board pack</a></li>
  </ul>
</div>
<div class="section">
  <h2>Downloads</h2>
  <ul id="downloads"></ul>
</div>
<script>
// List PDF files if served dynamically; static fallback
document.getElementById('downloads').innerHTML = '<li><a href="downloads/">View all PDFs</a></li>';
</script>
</body>
</html>
INDEXEOF

# Build manifest with timestamp and commit info
COMMIT=$(git -C "$SURFACE_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
COMMIT_MSG=$(git -C "$SURFACE_ROOT" log -1 --format=%s 2>/dev/null || echo "")
cat > "$SITE_DIR/downloads/BUILD.txt" << EOF
WARNING: This directory is auto-generated by Surface (company-as-code).
All files here are overwritten on every build. Do not edit manually.

Built:  $(date -u '+%Y-%m-%d %H:%M:%S UTC')
Commit: $COMMIT — $COMMIT_MSG
Source: https://git.zolanic.space/formabi/surface
EOF

echo "==> Site built at $SITE_DIR"
ls -la "$SITE_DIR"
